name: BroadcasterUpdate

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Command for release of version'
        required: true
        default: '--release-as minor'

jobs:
  update:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./broadcaster
    steps:
      - name: Checkout to code
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 14.10.0
      - name: Install dependencies
        run: yarn install
      - name: Bump Veue Broadcaster Version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "Input Value ${{ github.events.inputs.release }}"
          yarn updateversion -- ${{ github.events.inputs.release }}
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
          