name: BroadcasterRelease

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Command for release of version'
        required: true
        default: '--release-as minor'

jobs:
  dist:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./broadcaster
    steps:
      - name: Checkout to code
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 14.10.0
      - name: Install dependencies
        run: yarn install
      - name: Bump Veue Broadcaster Version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo "Input Value ${{ github.event.inputs.release }}"
          yarn updateversion -- ${{ github.event.inputs.release }}
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
      - name: Build Veue Broadcaster
        env:
          ELECTRON: true
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_SECRET}}
          CSC_LINK: ${{secrets.CSC_LINK}}
          CSC_KEY_PASSWORD: ${{secrets.CSC_KEY_PASSWORD}}
          WIN_CSC_LINK: ${{secrets.WIN_CSC_LINK}}
          WIN_CSC_KEY_PASSWORD: ${{secrets.WIN_CSC_KEY_PASSWORD}}
        run: yarn release
